version: "3.8"
services:
  asterisk:
    build: .
    image: asterisk20-chansip
    container_name: asterisk20
    ports:
      - "5060:5060/udp"          # Puerto SIP UDP
      - "10000-10010:10000-10010/udp"  # RTP de audio
    volumes:
      - ./config/sip.conf:/etc/asterisk/sip.conf
      - ./config/extensions.conf:/etc/asterisk/extensions.conf
      - ./config/modules.conf:/etc/asterisk/modules.conf
      - ./logs:/var/log/asterisk
      
